### ISSUE TITLE
Could the authors share the trained model?

### ISSUE THREAD

**Issue by linshuheng6** [amirmk89/gepc#1]
Hi,
Thank you for your great work on anomaly detection. I am interested in this paper. Could you please share the trained model? 

Thank you!

**Comment by zzchust** [comment]
+1

**Comment by zzchust** [comment]
+2

**Comment by amirmk89** [comment]
Thank you for your comments. I am unable to get to the university these days due to public restrictions. When they are over I will be able to share the model.

**Comment by marco-rudolph** [comment]
Is there any update?

**Comment by amirmk89** [comment]
Hi,

Sorry for the late reply, I'm no longer a part of the lab in which the work
was done in, and haven't been able to get access.
