### ISSUE TITLE
Number of keypoints in provided poses / graph 

### ISSUE THREAD

**Issue by johannathiemich** [amirmk89/gepc#9]
Hi,

first of all thank you for providing this great repository! It has been of great help.
However, there is just one thing that I do not quite understand.
In the file models/graph/graph.py, in the get_edge method you define the layout of the format 'openpose' which is the default format that is used. For openpose, the number of nodes is defined as 18, which makes sense when assuming that you used the following topology:

![openpose_18](https://user-images.githubusercontent.com/23737605/118809596-1a97b380-b8ab-11eb-9b60-bd3e7b9310f8.png)

But when looking at the provided pose files, there are only 17 keypoints in each track. 
Did you leave out a keypoint each time? Or was it a different topology that you used? I am trying to generate the keypoints for another dataset using Alphapose and would be very glad if you could confirm the settings that you used for generating the poses. I would also be interested in what you used for tracking. 

Thanks a lot!

**Comment by johannathiemich** [comment]
I solved this, the topology shown in the picture was used. The 18th keypoint was added manually.

**Comment by alessandra3265** [comment]
do you know how the json files were obtained? or what their meaning is? They have a structure of the type: 

file : "01_001_alphapose_tracked_person.json"

    ├── "1"
        ├── "0001"
            ├── "keypoints" 
            └── "scores" 
        ├── ...
        └── "0332"
    ├── ...
    └── "9"



but the output of openPose is different i.e.:

file "openPose_output.json":


{'people': [{'face_keypoints_2d': [],
   'face_keypoints_3d': [],
   'hand_left_keypoints_2d': [],
   'hand_left_keypoints_3d': [],
   'hand_right_keypoints_2d': [],
   'hand_right_keypoints_3d': [],
   'person_id': [-1],
   'pose_keypoints_2d': [77.5658, ...., 0,0,0],    _//first person keypoints_
   'pose_keypoints_3d': []},
  {'face_keypoints_2d': [],
   'face_keypoints_3d': [],
   'hand_left_keypoints_2d': [],
   'hand_left_keypoints_3d': [],
   'hand_right_keypoints_2d': [],
   'hand_right_keypoints_3d': [],
   'person_id': [-1],
   'pose_keypoints_2d': [0, 0,159.735,33.2..., 0], _//second person keypoints_
   'pose_keypoints_3d': []}],
 'version': 1.3}
